### ISSUE TITLE
Not working with python 2.6

### ISSUE THREAD

**Issue by pztop** [VREMSoftwareDevelopment/rstats-cstats#2]
I tried on a CentOS 6 with python 2.6 and the script failed:

```
#python rstats.py tomato_rstats_488b3939cdb9.gz 
>>>>>>>>>> Tomato USB RSTATS <<<<<<<<<<
Traceback (most recent call last):
  File "rstats.py", line 120, in <module>
    main()
  File "rstats.p", line 113, in main
    RStats(args[0]).dump()
  File "rstats.py", line 43, in __init__
    with gzip.open(filename, 'rb') as fileHandle:
AttributeError: GzipFile instance has no attribute '__exit__'
```

Tired on Ubuntu 16.04 with python 2.7 and it works fine.

**Comment by VREMSoftwareDevelopment** [comment]
The code was designed to work with python 2.7. And was tested using Linux and Windows.
